from .few_shot import FEW_SHOT_PROMPT_TEMPLATE
from .level_prompt import LEVEL_PROMPT_TEMPLATE
from .zero_shot import ZERO_SHOT_PROMPT_TEMPLATE

__all__ = ['ZERO_SHOT_PROMPT_TEMPLATE', 'LEVEL_PROMPT_TEMPLATE', FEW_SHOT_PROMPT_TEMPLATE]